//Day 2 - data types
//Two types: primitive and non primitive or OBJECTS

//Primitive:
//numbers, strings, bools, null, undefined, symbol (a unique value that can be generated by Symbol constructor)
//non: objects and arrays


//once a primitve data type is created we cannot modify it
let word = 'Javascript'
console.log(word)
word[0] = 'Y'
console.log(word)

//Strings are immutable


//how about numbers?
let numOne = 3
let numTwo = 3
console.log(numOne == numTwo)      // true
numTwo = 4
console.log(numOne == numTwo)      // false
//the number changed!